name: Test pull_request synchronize trigger.

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - main
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Triggered
        run: echo "Triggered"
      - name: Display context
        run: echo '${{ toJSON(github) }}'
